name: CI

on: [push, pull_request]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql_analysis:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'python'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ... other jobs ...
