name: CI

on: [push, pull_request]

jobs:
  codeql_analysis:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'python'  # Specify the languages to analyze

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    needs: codeql_analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest
    needs: codeql_analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: latest

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PWD }}

      - name: Docker Scout Scan
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview
          docker scout cves

  dast_scan:
    name: Run ZAP Automation Framework Scan
    runs-on: ubuntu-latest
    needs: codeql_analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: ZAP Scan
        uses: zaproxy/action-af@v0.2.0
        with:
          plan: '.github/workflows/zap/plan.yml'
